-- CreateTable
CREATE TABLE "Desa" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nama" TEXT NOT NULL,
    "kode" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "Surat" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nomor" TEXT NOT NULL,
    "perihal" TEXT NOT NULL,
    "tanggal" DATETIME NOT NULL,
    "desaId" INTEGER NOT NULL,
    "anggaran" DECIMAL NOT NULL DEFAULT 0,
    "tipe" TEXT NOT NULL DEFAULT 'KELUAR',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Surat_desaId_fkey" FOREIGN KEY ("desaId") REFERENCES "Desa" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "Desa_nama_key" ON "Desa"("nama");
